### ISSUE TITLE
cant change simcard with simtoolkit

### ISSUE THREAD

**Issue by swapper-zz** [CyanogenDefy/android_device_motorola_jordan#10]
I use in my defy a dual simcard adapter which allows me to switch between two simcards. On 2.2 (Pay roms) this is no problem with the app simtoolkit wich automaticly appears in the appdrawer.
On CM7 an MIUI this dosent work anymore. I start the app choose the other simcard and nothing happens.

**Comment by swapper-zz** [comment]
a user in xda said that it works with beta 5. all newer versions arent compatible. Why?

**Comment by Seraphiel** [comment]
Hi I have exactly the same problem. with froyo my simcard worked fine, but with the newest CM7 RC01 it does not work anymore.
Is it possible to fix this issue at cm7 ? I like this ROM it´s so cool and effective.
Please support 
Regards Seraphiel

**Comment by maniac103** [comment]
I don't have a dual sim adapter myself, so I can't test, but can anyone of you provide the output of adb logcat while attempting the card switch so we can check whether there is some glaringly obvious problem?

**Comment by swapper-zz** [comment]
ok i loged it with alogcat on 2.2 and cm7 (.txt file)

2.2 log:
http://www.multiupload.com/GKMLRVEFJ0

on cm7 it does nothing: 

D/alogcat ( 3423): stopping ...
D/alogcat ( 3423): stopped
D/alogcat ( 3423): starting ...
D/dalvikvm( 3104): GC_EXPLICIT freed 127K, 50% free 3150K/6279K, external 5988K/7054K, paused 80ms
V/alogcat ( 3423): save instance
V/alogcat ( 3423): paused
D/alogcat ( 3423): stopping ...
D/alogcat ( 3423): stopped
D/alogcat ( 3423): stopping ...
D/alogcat ( 3423): canceling periodic saves
V/alogcat ( 3423): started
V/alogcat ( 3423): resumed
D/alogcat ( 3423): starting ...
V/alogcat ( 3423): save instance
V/alogcat ( 3423): paused
D/alogcat ( 3423): stopping ...
D/alogcat ( 3423): stopped
D/dalvikvm( 3104): GC_EXTERNAL_ALLOC freed 116K, 50% free 3172K/6279K, external 6512K/6564K, paused 77ms
D/dalvikvm( 3423): GC_EXPLICIT freed 345K, 52% free 2801K/5767K, external 777K/1289K, paused 69ms
D/dalvikvm( 3104): GC_EXPLICIT freed 32K, 50% free 3144K/6279K, external 6402K/7454K, paused 54ms
D/alogcat ( 3423): stopping ...
D/alogcat ( 3423): canceling periodic saves
V/alogcat ( 3423): started
V/alogcat ( 3423): resumed
D/alogcat ( 3423): starting ...

**Comment by maniac103** [comment]
Fixed now: https://github.com/CyanogenDefy/android_frameworks_base/commit/733d9a018f1e50ab6f37882f195b8467dd07159f
