### ISSUE TITLE
wifi doesn't work ......

### ISSUE THREAD

**Issue by BadRomance** [CyanogenDefy/android_device_motorola_jordan#100]
wifi keeps searching but no hotspot shown .

old hotspot : out of searching area ( even my home's router wifi said this ! )

**Comment by BadRomance** [comment]
cm7 nightlies 1.5

**Comment by charlie2alpha** [comment]
I would recommend that you try the latest BOOTWIFI nightly, it has a new WiFi module that seems to solve some problems.

**Comment by BadRomance** [comment]
boot 179 ??

**Comment by charlie2alpha** [comment]
No, this one: http://defycm7.tanguy.tk/cm7-110905-1941-BOOTWIFITEST-Jordan.zip

**Comment by BadRomance** [comment]
even boot 179 do the same !!!!
i don't have wifi now !
do i need to flash 2.2 then up cm7 again >?

**Comment by charlie2alpha** [comment]
My suggestion is to flash the one I linked in my previous comment and delete /data/misc/wifi/wpa_supplicant.conf and reboot. I do not have WiFi problems with that nightly.

**Comment by BadRomance** [comment]
i will try it . thanks
