### ISSUE TITLE
WIFI "N" it is not connected

### ISSUE THREAD

**Issue by sergnc** [CyanogenDefy/android_device_motorola_jordan#101]
RC 1.5 doesn't work with type "N" points WIFI.There are 2 mens have this problems.

**Comment by jonyfs** [comment]
I have the same problem.

**Comment by mlukim** [comment]
I also had problems in RC1.5 but it was problem with WPA2 protocol with AES ecryption (on N and B/G)
For me problem was solved after instaling cm7-110911-1924-BOOTWIFI3-Jordan nightly.
