### ISSUE TITLE
RC 1.5 No network in 2G mode

### ISSUE THREAD

**Issue by manamohana** [CyanogenDefy/android_device_motorola_jordan#105]
I installed RC 1.5, there is no network in 2G mode. When switched back to 3G network is good still i found few sticks drop and fluctuating.

**Comment by charlie2alpha** [comment]
Cannot confirm this, worked fine in Rc1.5 and the latest nightlies too. Do you have the correct baseband set?

**Comment by manamohana** [comment]
i just installed it. did not change any base band. only 3g mode was getting signal when i used just 2g no signal.

**Comment by charlie2alpha** [comment]
If this is your first install of CyanogenMod on this device, it is necessary to select the correct baseband with the Baseband Switcher app (included in CM7).

**Comment by manamohana** [comment]
i was using cm7 rc1, about 3 days back i replaced it with jboogie 3 liquidarc because i have posted before i have some problems with force closing of google map. today i found out about new cm7 1.5 switched back to cm7 now shall i just restore the backup file of rc1v2 and then intall this rc1.5? guide me here and have u faced force close issue of google maps? Right now im using rc1v2.

**Comment by charlie2alpha** [comment]
No need to revert, all you need it to open Baseband switcher and select correct baseband for your carrier. I will test the Maps.

**Comment by manamohana** [comment]
google map work fine for a day once u restart then it will start force closing and hangs the phone and phone will restart. now im in base band switcher app there is americas emea and apac wht should i do now?

**Comment by charlie2alpha** [comment]
Ok, there is a problem with Maps, after a while it becomes slow (sluggish) and then it stops responding. The developers are aware of the problem from what I know.

**Comment by manamohana** [comment]
s is this problem still there in this new rc1.5? im using base band switcher now what should i do now will it correct the base band by itself??

**Comment by charlie2alpha** [comment]
What country are you in? EMEA = Europe & Middle East, Americas is obvious, APAC is Asia Pacific regions.
Yes, the problem with the Maps is also in the latest nightlies.

**Comment by manamohana** [comment]
apac region

**Comment by charlie2alpha** [comment]
You need to select one from there then, corresponding to your country and/or carrier.

**Comment by manamohana** [comment]
s got it thanx a lot.

**Comment by manamohana** [comment]
Hi,
 If ur using latest stable cm7 2.3.7 can u tell me even in this stable ROM google map force closing problem exist.. I'm facing this issue even in this ROM..

Sent from Yahoo! Mail on Android
