### ISSUE TITLE
cant change the colour of the notification bar background or transparency. his was possible on the milestone

### ISSUE THREAD

**Issue by nadejo** [CyanogenDefy/android_device_motorola_jordan#114]

**Comment by AL2** [comment]
This is not a bug on CM7; just that the option is unavailable.
This issue should be closed.

For a matter of fact, I do have my notification bar transparent at this very moment and I'm using RC1.5...
So search the forum and you will find a way to do it. 
This might help you: http://forum.xda-developers.com/showthread.php?t=1261061 to start.
