### ISSUE TITLE
Extralow download speed in "Moto Portal" app

### ISSUE THREAD

**Issue by Kpyto** [CyanogenDefy/android_device_motorola_jordan#117]
Moto Portal seems to work good, but when you try to download the photo speed is 4-6Kb\sec.

Photo proof:  http://i.piccy.info/i7/6bac9c59281a34066e5a799fda466060/1-5-151/23211011/speed.jpg

While usind Moto Portal without downloading anything is ok.  Wi-fi speed in Browser is good too.

Build cm7-110923-0710-NIGHTLY-Jordan.zip

**Comment by Kpyto** [comment]
Bug confirmed in cm7-110928-2257-NIGHTLY

**Comment by Quarx2k** [comment]
fixed

**Comment by Kpyto** [comment]
Cool, thanks! Unfortunately I'm moved from Motorola Defy to Samsung Nexus S, will check CM for it :)
