### ISSUE TITLE
bug with long press headset through sleep mode

### ISSUE THREAD

**Issue by ncc-1701** [CyanogenDefy/android_device_motorola_jordan#118]
This problem is shown in following cases:

1) When I try to end call by long  press in sleep mode – it recognized by system like short press (instead command to end call executed command mute microphone).

2) When I try to switch next track in player by long press (used Music PlayerPro, which has this ability to use long press headset button), it recognized by system like short press too (executed command pause/play).

Additional info:

device: Motorola Defy
system: CyanogenMod 7 (Android 2.3.5)  RC1.5

Please, resolve the problem of recognition long press headset button in sleep mode

**Comment by tpruvot** [comment]
https://github.com/CyanogenDefy/android_frameworks_base/commit/82f9b34dd9408c8c52f1a3cb926dde652b45025c
