### ISSUE TITLE
2g Network doesn't work

### ISSUE THREAD

**Issue by larrybml** [CyanogenDefy/android_device_motorola_jordan#13]
When I try to use 2G network only, for saving battery, the signal disappear , when I'm using GSM/WCMDA the signal is very unstable, discharging quickly battery and the phone goes hot.

**Comment by charlie2alpha** [comment]
Have you selected the proper baseband? I have no such problem.

**Comment by larrybml** [comment]
Sorry for my question, but how can I do that ? In phone specifications is writen that phone is capable for :

2G Network GSM 850 / 900 / 1800 / 1900  
3G Network HSDPA 900 / 2100  
  HSDPA 1700 / 2100 or HSDPA 850 / 1900 

My mobile carrier is Cosmote RO, and searching on the net I found that is using 900 and 1800 frequency bands. Now, how can I set this phone tu use only GSM bands, not WCDMA. Please help me.

**Comment by charlie2alpha** [comment]
Use the baseband switcher app, it is pre installed in Cyanogenmod. Select the Central Europe baseband.

**Comment by larrybml** [comment]
Thank you, that work.

**Comment by charlie2alpha** [comment]
Glad to be of help! Since your problem is solved, please close this issue (click the "close issue" button!).
