### ISSUE TITLE
Camera hangs during video recording when STOP RECORDING button pressed. 

### ISSUE THREAD

**Issue by darmach** [CyanogenDefy/android_device_motorola_jordan#135]
Camera hangs during video recording when STOP RECORDING button pressed. When killed - unable to start camera app until reboot - it crashes with error: unable to comunicate with camera.

Versions in which i encountered it:
cm7-20111021-NIGHTLY-Defy.zip   2011-Oct-21 06:57:04    97.6M   application/zip
cm7-20111024-NIGHTLY-Defy.zip   2011-Oct-24 10:53:46    97.6M   application/zip

**Comment by loosethisskin** [comment]
Update to cm71-111108.0452-NIGHTLY-Defy. This nightly fixes the issue.
