### ISSUE TITLE
How to commit my code.

### ISSUE THREAD

**Issue by GodFox** [CyanogenDefy/android_device_motorola_jordan#145]
Hello! I have finish the translation for framework in Chinese. But I did not know how to commit it. Shall I commit them to the http://review.cyanogenmod.com or other place?
Please help me ! Thank you!

**Comment by SunRain** [comment]
Hmm, I think it is better to push it to your own repo,then click "pull request" button to push it.
深邃？先提交到你自己的git上，然后点击”pull request“提交到你folk的那个repo上面去。
不过你要自己提交到cm的这个review应该也可以的

**Comment by GodFox** [comment]
泪泪。。。O(∩_∩)O哈哈~
还是中文看着舒服。。。
CM的review没有defy单独分出来的framework，我还是提交到这里吧。。。
谢啦。。。
