### ISSUE TITLE
Phone Dialer doesn't check existing numbers

### ISSUE THREAD

**Issue by larrybml** [CyanogenDefy/android_device_motorola_jordan#149]
I have a problem with the Phone alpication (dialer) in preference we have a button caled : Disable number checks , witch does nothing. I want my phone to show me contacts from phone book when I start to dial a number. What can I do?

**Comment by maniac103** [comment]
You can wait for ICS (its dialer will have that feature) or install an alternative dialer from the market, e.g. Dialer One.
