### ISSUE TITLE
camera not focusing in low light

### ISSUE THREAD

**Issue by supersebius** [CyanogenDefy/android_device_motorola_jordan#15]
the camera doesn´t turn on the led  while focusing in very low light neither on RC0 nor cm7-110623-1927-BOOT179-Jordan.zip . that means the camara can´t focus in very low light

that was functional on the stock froyo rom.

**Comment by maniac103** [comment]
It's likely the same issue as for #24.

**Comment by maniac103** [comment]
Closing this one, we'll track the LED problems in #24.
