### ISSUE TITLE
wi fi dead

### ISSUE THREAD

**Issue by seukumeama** [CyanogenDefy/android_device_motorola_jordan#152]
my wi fi just dont work i cant list or connect and teh probable soluction i cant found because this option dont  exist anymore

Settings>networks>wifi>menu button>advanced>regulatory domain>14 channels. 

i remeber this was present on previous versions of nighlys but now was gone 

tks in advanced

**Comment by seukumeama** [comment]
i on latest nightly  of xda  , and i tried the official cyano build but no sucess

actually on cm72-111115.0500-NIGHTLY-Defy.zip

**Comment by charlie2alpha** [comment]
There is a way to re-enable that option, but you must edit system files, not recommended. Make sure your Network is on a channel equal or below channel 11 and delete /data/misc/wifi/wpa_supplicant.conf and reboot the device.

**Comment by seukumeama** [comment]
MAN  really really tanks , the option wont back but this solve my problem

**Comment by seukumeama** [comment]
i dont no why , but this
