### ISSUE TITLE
Music title not showed in lockscreen

### ISSUE THREAD

**Issue by feywang** [CyanogenDefy/android_device_motorola_jordan#155]
i installed Music 4.0 which is new from google.
but it didn't show the title of the playing music in lockscreen like the Music integrated in CM ROM.

would anyone fix that please~~The Music 4.0 is really a major update.

**Comment by maniac103** [comment]
It's not possible to fix that, the Google Music app just doesn't provide the details of the played song to other apps.

**Comment by feywang** [comment]
all right, thanks anyway :)

looking foward to official release of CM9! on defy

On Fri, Feb 3, 2012 at 5:27 PM, maniac103
reply@reply.github.com
wrote:

> It's not possible to fix that, the Google Music app just doesn't provide the details of the played song to other apps.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/CyanogenDefy/android_device_motorola_jordan/issues/155#issuecomment-3793993

## 

王霏 (Fey WANG)
