### ISSUE TITLE
No PIN code eneter panel

### ISSUE THREAD

**Issue by artemstorozhuk** [CyanogenDefy/android_device_motorola_jordan#175]
When turn off lock screen (in settings->cyan->tablet) and reboot phone the PIN code pannel doesn't appear at all. But with lock screen it appears at startup.

**Comment by artemstorozhuk** [comment]
Another guy with defy has confirmed this bug.

**Comment by maniac103** [comment]
This is fixed now: http://review.cyanogenmod.com/#change,13336
