### ISSUE TITLE
GPS is very weak

### ISSUE THREAD

**Issue by eversonleal** [CyanogenDefy/android_device_motorola_jordan#18]
Hi everyone,I'm having this problem in the Google Navigator, when driving in any weather condition the application tells me that the GPS signal has lost. Sometimes using the UlysseGizmo app for the GPS test it don't found any satellite.

**Comment by killigrew** [comment]
find a gps.conf for your country or region, try google or xda search for that.

**Comment by javyyk** [comment]
@killigrew

Are you saying we should config the gps according to our country?

**Comment by killigrew** [comment]
don't know, if it helps you, then yes, if it doesn't, then no, but it can help and i am doing it!

**Comment by antonyps** [comment]
There's instructions in CyanogenMod FAQ in xda on how to correct this behaviour.

**Comment by silvanspirit** [comment]
@antonyps what instructions? do you mean changing the NTP pool server to one that is relevant for your country? this only reduces the time to get a fix, but doesn't address the issue that the actual fix is unsteady at best. leaving the phone lying somewhere, you can see that the numer of fixed sats is fluctuating wildly every few seconds, sometimes losing lock while seeing 4-6 sats.

**Comment by eversonleal** [comment]
I've tried to set some NTP servers that's relevant to my country (Brazil), but the GPS precision keeps low.

**Comment by javyyk** [comment]
http://forum.xda-developers.com/showthread.php?t=1065798

Point number 13

**Comment by charlie2alpha** [comment]
This issue persists since beta6, the gps.conf fix is useless, the best it can do is to speed up a little the initial locking time, it _cannot_ improve accuracy. 

I'm suspecting it's either a kernel driver issue, OR an issue with the Motorola proprietary location proxy code, which we can't seem to be able to get rid of :(

**Comment by eversonleal** [comment]
So I tried to flash my phone to the original ROM (Froyo) and I cannot found the GPS.CONF file, then I've installed the CM7 RC1v2 again and executed the point 13 in FAQ and nothing yet. My GPS only locks when I lift up the phone to the sky. LOL

**Comment by coolwaves** [comment]
Oh, man. We are aproaching final releases and we haven't yet found a proper solution to this issue. I bet ccav2000 is right and we are dealing with a driver / motorola proxy problem here, as I have tried a lot of GPS fixes that use different NTP servers and tweaks, but the only effect they have is to speed up satellite locking but they do not increase accuracy at all. In fact the cost for earlier lock is to have even more inaccurate positions for the first 5 or 10 seconds...
