### ISSUE TITLE
Radio issues > RC0

### ISSUE THREAD

**Issue by jasontx** [CyanogenDefy/android_device_motorola_jordan#20]
I'm experiencing weak reception inside of my office. Before RC0 I would get 2-3 bars H or 3G and now I receive 1 E bar if I am lucky. Most times I have no service. If I am out of the office reception seems to be great.
I have performed a master reset and tried all of the T-MO US bands with the same result.

**Comment by jasontx** [comment]
When Wifi is disabled reception is as expected. I do not connect to wireless at work but most times just do not disable. I remember reading something about wireless issues in the new kernel. Were those fixed with the RC1 release or is there something that needs to be done?

**Comment by sidez** [comment]
I've noticed some power weakness of signals, is more noticeable on wifi but may affect 3g too sometimes, I'll pay attention on wifi+ 3g combination.
No problems with call reception at the moment.
I'm on RC1v2.

**Comment by jasontx** [comment]
Ok I had the wrong baseband selected, i appreciate your help sidez. Does not seem to be an issue.
