### ISSUE TITLE
Auto brightness and capacitive backlight keys - RC1

### ISSUE THREAD

**Issue by ghost** [CyanogenDefy/android_device_motorola_jordan#23]
Since I've updated from RC0 to RC1 today I've noticed that the automatic brightness settings make the screen's backlight be too low compared to RC0. 
Also, after the screen dims [after letting it sit for ~10 seconds] the capacitive key lights turn off. They can be however, turned on again by turning the screen off and on.

**Comment by maniac103** [comment]
You can configure the backlight adjustment steps to your liking under Settings -> CyanogenMod -> Display -> Automatic brightness -> Configure steps. You can also adjust the brightness up to which the buttons are lit there. Please note that on the Defy, it's not possible to adjust the button brightness, they can only be turned on and off.
