### ISSUE TITLE
Mp4 playback/ Video recording issues on RC1

### ISSUE THREAD

**Issue by vikrambharadwaj** [CyanogenDefy/android_device_motorola_jordan#26]
Hi, Just flashed the RC1 and I see mp4 playback issues. Some videos are too jerky and unwatchable most of the times.
Videos recorded with the defy itself suffer from the same issue.

**Comment by ghost** [comment]
I can confirm both the issues and say that the recording video frame drops it is a problem present from beta 6 version included.

**Comment by maniac103** [comment]
Duplicate of #5.

**Comment by ghost** [comment]
Yes, if you speak about the mp4 PLAYBACK issue, but the RECORDING issue is still present from beta 6 so probably it is not related to the palyback issue now appears in RC1 and the link you post only talks about palyback issue.
