### ISSUE TITLE
Two BUGs of camera setting, RC1

### ISSUE THREAD

**Issue by arcol** [CyanogenDefy/android_device_motorola_jordan#27]
1.advanced options -> Select "Long Focus" & "Search Button", The "Search Button" cannot work on "Long Focus"

2.advanced options -> Select "Volume Buttons Zoom", It works just "1x" and "6x", not "1x" to "6x" smoothly

**Comment by maniac103** [comment]
1. is already in the works: http://review.cyanogenmod.com/#change,6315

**Comment by maniac103** [comment]
Err, that meant to read item 2 is in the works, not item 1.

**Comment by maniac103** [comment]
I will include item 1 in the mentioned patch as well.

**Comment by maniac103** [comment]
Patch is merged now, thus the issue is fixed.
