### ISSUE TITLE
Mute sound mode

### ISSUE THREAD

**Issue by javyyk** [CyanogenDefy/android_device_motorola_jordan#29]
The silent mode does not synchronize well with the different menus where you can activate the muting mode

While at the menu of the power button (long press), the mute mode is enabled, at the sound settings, at phone settings, the silent mode is disabled, the menus do not synchronize well

CyanogenMod7 RC1

**Comment by maniac103** [comment]
This works just fine for me.
If it doesn't work for you, even after a data wipe, please report this issue in the main CyanogenMod bug tracker:
http://code.google.com/p/cyanogenmod/issues/list

We only track Defy-specific issues here.
