### ISSUE TITLE
apns-conf.xml is the old one

### ISSUE THREAD

**Issue by marhensa** [CyanogenDefy/android_device_motorola_jordan#3]
the apns-conf.xml which included on ROM is the old one.
had to reset apn setting each installing cm7 rom.

my carrier change its apn settings long time ago (about 2008).
and i think it's not only happen on my country.

why don't use the new apns-conf.xml that included on official rom?
it's the new one.. :)

here, i extract it from official froyo...
http://www.mediafire.com/?m9w16sbs1mrr492

**Comment by maniac103** [comment]
We're using the CyanogenMod provided one now, which should be newer.

**Comment by marhensa** [comment]
in the newer RC1 released today,
apns-conf.xml still the SAME OLD things...

apn carrier="Indosat" mcc="510" mnc="01" apn="indosat3g" user="indosat" password="indosat" type="default,supl"
apn carrier="Indosat MMS" mcc="510" mnc="01" apn="indosatmms" user="indosat" password="indosat" mmsc="http://mmsc.indosat.com" mmsproxy="10.19.19.19" mmsport="8080" type="mms"
^
that config should be no longer used since 2008 mate...

CM7 source is using old configuration, it is not updated on many countries.
please use apns-conf.xml from official froyo, it is newer!
i guaranteed!

**Comment by maniac103** [comment]
Please report this to the CM bug tracker: http://code.google.com/p/cyanogenmod/issues/list
We only track Defy-specific issues here.

**Comment by marhensa** [comment]
okay my bad..
thank you for your advice..
