### ISSUE TITLE
Mail - not gmail

### ISSUE THREAD

**Issue by zadziora** [CyanogenDefy/android_device_motorola_jordan#31]
Mail in RC1 is not working - no new mail is coming and one can not send mail.

**Comment by zxbodya** [comment]
I have tested it with gmail address, on rc1 - everything is ok for me..

**Comment by zadziora** [comment]
please read carefully - MAIL - NOT GMAIL

**Comment by zadziora** [comment]
Gmail is working.
Mail is not working to be more specific.

**Comment by zadziora** [comment]
I went to POP and SMTP settings again - it was not changed since it worked with RC0 and then I update to RC1 - I pressed [Next] and after this the new mails were in box. Weird but worked.
