### ISSUE TITLE
Display brightness in  camera application

### ISSUE THREAD

**Issue by zxbodya** [CyanogenDefy/android_device_motorola_jordan#32]
When using automatic display brightness and open camera application - display brightness is set to maximum value(no such error when using fixed display brightness).
Using RC1, on device with red lens(BAYER in log)

**Comment by cslucian** [comment]
i have the same problem on cm7-110627-1722-NIGHTLY-Jordan.zip
I have a green lens defy

**Comment by maniac103** [comment]
It's not a bug, it's done like that on purpose by Google:
http://android.git.kernel.org/?p=platform/packages/apps/Camera.git;a=commit;h=ed32015f4a0536e842306a207d620ec5e3f665c0
