### ISSUE TITLE
Illogical simultaneous running of FM radio 2.1 with Music/Video Players

### ISSUE THREAD

**Issue by LeopardSurd** [CyanogenDefy/android_device_motorola_jordan#35]
There is one demand: it is possible that the multimedia apps that use sound output like Android Player, Player Pro, FM Radio or any other Video player (they play audio encoded files from sdcard or use radio) to stop when another mutimedia app is started?

For example I use FM Radio to listen radio and I want to open my favorite music player (Player Pro). In this case, I just wanna that FM Radio to stop automaticaly (until I'll open it again) when I push play button in ProPlayer.

This kind of interaction, I've observed at Connected Music Player in stock Moto Defy ROM: enabling radio disable music player and vice versa. 

At least, this option is useful for FM-Music Player co-existence. For Videos, I admit that there could be someone who'd wanna listen music in the same time with a muted video.

**Comment by maniac103** [comment]
This kind of interaction is only possible if both media sources (here: FM, music) are played in one app. This isn't the case for our ROM, and we don't have the sources of the FM radio app, which complicates things even further.

Hence, we can't fix this. You should be able to use the connected media player in CM7, though (search xda forums for it, I definitely saw it posted somewhere).
