### ISSUE TITLE
sysctl min_free_kbytes 2845 is again

### ISSUE THREAD

**Issue by vick33** [CyanogenDefy/android_device_motorola_jordan#39]
min_free_kbytes is back on stock 2845 in the latest nightlys causing instability in 3d apps. Could you change it back to 4096. 
And the 0 for dirty ratio does not seems too good for me too. Thx for looking into it:-)

**Comment by charlie2alpha** [comment]
Seems I got hit by this while using Google Maps for an extended period of time (e.g. more than 10 seconds ^^).

**Comment by silvanspirit** [comment]
+1 (me too..)

**Comment by Quarx2k** [comment]
Changed to 4096
https://github.com/CyanogenDefy/android_device_motorola_jordan/commit/513bb8e86ba2c52a0286a604933e6936a7afb067
