### ISSUE TITLE
wifi reboot

### ISSUE THREAD

**Issue by micsuka** [CyanogenDefy/android_device_motorola_jordan#40]
I'm just wondering if someone else has a similar problem with the wifi like this.
I KNOW that it's a kernel issue and it's not a cyanogenmod issue. But there are defy hackers here and maybe someone would have a workaround.

So.... when switching the wifi on, my phone reboots. Often.
I've managed to catch a dmesg regarding the problem:

<6>[  343.841766] TIWLAN: driver init
<6>[  343.841857] TIWLAN SDIO init
<4>[  343.841979] in sdio_init() sdcnum= 3 
<4>[  343.842254] in sdioDrv_init(), before platform_driver_register(&sdioDrv_struct)
<6>[  343.842498] TIWLAN SDIO probe: initializing mmc3 device
<4>[  343.842712] Configuring SDIO DMA registers!!!
<4>[  343.842803] pdev->id is 2!!!
<1>[  343.865234] Unable to handle kernel paging request at virtual address be000008
<1>[  343.865417] pgd = da860000
<1>[  343.865509] [be000008] *pgd=00000000
<0>[  343.865753] Internal error: Oops: 805 [#1] PREEMPT
<0>[  343.865844] last sysfs file: /sys/devices/virtual/timed_output/vibrator/enable
<4>[  343.865997] Modules linked in: tiwlan_drv(+) cifs slow_work(P) nls_utf8 tun kineto_gan sec modem_pm_driver netmux_linkdriver netmux overclock [last unloaded: tiwlan_drv]
<4>[  343.867248] CPU: 0    Tainted: P            (2.6.32.9-gbc356f0 #1)
<4>[  343.867401] PC is at 0xd68df400
<4>[  343.867492] LR is at 0xd68df3cc
<4>[  343.867584] pc : [<d68df400>]    lr : [<d68df3cc>]    psr: a0000013
<4>[  343.867584] sp : d533fea8  ip : 000000d0  fp : 40b0ec20
<4>[  343.867828] r10: c8e5e800  r9 : d533e000  r8 : 00000008
<4>[  343.868011] r7 : 00000040  r6 : 00000014  r5 : 00000008  r4 : c8cc9a00
<4>[  343.868103] r3 : 6d656d65  r2 : a0000013  r1 : a0000013  r0 : 000007a1
<4>[  343.868255] Flags: NzCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment user
<4>[  343.868347] Control: 10c5387d  Table: 9b460019  DAC: 00000015
<4>[  343.868499] 
<4>[  343.868499] PC: 0xd68df380:
<4>[  343.868682] f380  00000000 2f6d6574 c00c4f14 00000008 6d656d73 c0084038 c8cc9a00 6d656d65
<4>[  343.869567] f3a0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[  343.870452] f3c0  7379732f 2f6d6574 2f6e6962 6b6e696c c8007265 c0084038 00000000 00000000
<4>[  343.871276] f3e0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[  343.872161] f400  d7082c80 00000040 00000002 00000040 00000004 c01dbc80 c01dbcd8 00000000
<4>[  343.873046] f420  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[  343.873931] f440  00000000 00000006 ded474c0 00000004 00000000 c0084038 00000000 00000000
<4>[  343.874786] f460  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[  343.875671] 
<4>[  343.875671] LR: 0xd68df34c:
<4>[  343.875823] f34c  d7240000 00000001 ffffffff 00000000 ffffffff 00000000 00000000 00000000
<4>[  343.876739] f36c  00000000 00000000 00000000 00000000 00000000 00000000 2f6d6574 c00c4f14
<4>[  343.877624] f38c  00000008 6d656d73 c0084038 c8cc9a00 6d656d65 00000000 00000000 00000000
<4>[  343.878540] f3ac  00000000 00000000 00000000 00000000 00000000 7379732f 2f6d6574 2f6e6962
<4>[  343.879364] f3cc  6b6e696c c8007265 c0084038 00000000 00000000 00000000 00000000 00000000
<4>[  343.880249] f3ec  00000000 00000000 00000000 00000000 00000000 d7082c80 00000040 00000002
<4>[  343.881164] f40c  00000040 00000004 c01dbc80 c01dbcd8 00000000 00000000 00000000 00000000
<4>[  343.882049] f42c  00000000 00000000 00000000 00000000 00000000 00000000 00000006 ded474c0
<4>[  343.882873] 
<4>[  343.882873] SP: 0xd533fe28:
<4>[  343.883117] fe28  00000000 df807000 00006fff c05ce010 000200d2 000002cf d522f340 e0fe6fff
<4>[  343.883911] fe48  c8cc9a00 ffffffff d533fe94 00000014 00000040 c0035a6c 000007a1 a0000013
<4>[  343.884826] fe68  a0000013 6d656d65 c8cc9a00 00000008 00000014 00000040 00000008 d533e000
<4>[  343.885711] fe88  c8e5e800 40b0ec20 000000d0 d533fea8 d68df3cc d68df400 a0000013 ffffffff
<4>[  343.886596] fea8  00000008 c8cc9a00 c8cc9a00 c8cc9a08 d533e000 c8e5e800 40b0ec20 bf17ec58
<4>[  343.887420] fec8  d6ed5014 c8cc9a00 c8cc9a04 bf182268 d6feca14 c8cc9a00 c8cc9a04 bf176e98
<4>[  343.888336] fee8  00000002 00000020 40b0ec20 c0344888 c0692578 c9826c80 c8cc9a00 00000000
<4>[  343.889221] ff08  c8cc9a00 00000000 c8cc9b20 bf2281b8 c8cc9ad8 bf2441ac c8cc9a0c c8cc9a10
<4>[  343.890045] 
<4>[  343.890045] R4: 0xc8cc9980:
<4>[  343.890289] 9980  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[  343.891204] 99a0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[  343.892028] 99c0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[  343.892913] 99e0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[  343.893798] 9a00  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[  343.894622] 9a20  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[  343.895538] 9a40  00000000 00000000 00000000 00000000 d51b1140 00000000 c8cc9a58 c8cc9a58
<4>[  343.896362] 9a60  bf1702d0 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[  343.897247] 
<4>[  343.897247] R9: 0xd533df80:
<4>[  343.897399] df80  c00360c4 0023a988 00000000 ffffffff 000000fc c00360c4 d533c000 47134f1c
<4>[  343.898315] dfa0  aca9f368 c0035f40 0023a988 00000000 0000007d 480cd9f8 00000010 ffffffff
<4>[  343.899139] dfc0  0023a988 00000000 ffffffff 000000fc 00000000 00000014 47134f1c aca9f368
<4>[  343.900024] dfe0  a812be6c 480cd9d0 a812558f afd0c5bc 20000010 0000007d ffffffff ffffffff
<4>[  343.900848] e000  00000000 00000002 00000000 d5330940 c0583030 00000000 00000017 d5330940
<4>[  343.901763] e020  c0582b20 d533e000 d5330bf0 c8cd8a00 dba5e800 dba10cc0 d533fdcc d533fd78
<4>[  343.902587] e040  c0417438 00000000 00000000 00000000 00000000 00000000 01010000 00000000
<4>[  343.903472] e060  47ecdf00 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[  343.904357] 
<4>[  343.904357] R10: 0xc8e5e780:
<4>[  343.904510] e780  00002ab8 0000012a 00002ac0 0000012a 00002ac0 00027b00 00002ac8 0000012a
<4>[  343.905426] e7a0  00002ad0 0000012a 00002ad0 000a6b00 00002ad4 0000072a 00002ad8 0000012a
<4>[  343.906311] e7c0  00002ad8 00027b00 00002ae0 0000012a 00002ae8 0000012a 00002af0 0000012a
<4>[  343.907135] e7e0  00002af8 0000012a 00002b00 0000012a 00002b08 0000012a 00002b10 0000012a
<4>[  343.908050] e800  6c776974 00306e61 00000000 00000000 00000000 ded1fb1c 00000000 00000000
<4>[  343.908935] e820  00000000 00000000 00000000 00000000 00000006 c06925b0 ddb79c34 c8e5e83c
<4>[  343.909820] e840  c8e5e83c 00000000 0000000f 0000000f 00000000 00000000 00000000 00000000
<4>[  343.910644] e860  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<0>[  343.911529] Process WifiService (pid: 2183, stack limit = 0xd533e2e8)
<0>[  343.911712] Stack: (0xd533fea8 to 0xd5340000)
<0>[  343.911804] fea0:                   00000008 c8cc9a00 c8cc9a00 c8cc9a08 d533e000 c8e5e800
<0>[  343.911956] fec0: 40b0ec20 bf17ec58 d6ed5014 c8cc9a00 c8cc9a04 bf182268 d6feca14 c8cc9a00
<0>[  343.912048] fee0: c8cc9a04 bf176e98 00000002 00000020 40b0ec20 c0344888 c0692578 c9826c80
<0>[  343.912231] ff00: c8cc9a00 00000000 c8cc9a00 00000000 c8cc9b20 bf2281b8 c8cc9ad8 bf2441ac
<0>[  343.912384] ff20: c8cc9a0c c8cc9a10 c8cc9a14 c8cc9a18 c8cc9a1c c8cc9a24 c8cc9a20 e50bda54
<0>[  343.912567] ff40: bf223678 bf244000 00000000 00000000 001048a8 c00360c4 470d5e9c c003537c
<0>[  343.912658] ff60: bf22c81c 00000000 a7e02e58 001048a8 c00360c4 bf22c81c 00000000 a7e02e58
<0>[  343.912811] ff80: 001048a8 c0092fdc 49aab008 001048a8 a7e02e58 49aab008 a7e02e58 47ecdc10
<0>[  343.912994] ffa0: 00000080 c0035f40 49aab008 a7e02e58 49aab008 001048a8 a7e02e58 00000001
<0>[  343.913146] ffc0: 49aab008 a7e02e58 47ecdc10 00000080 47ecdb68 470d5eb0 470d5e9c 40b0ec20
<0>[  343.913238] ffe0: a7e0421c 47ecdac8 a7e02b0d afd0c4cc 20000010 49aab008 00000000 00000000
<0>[  343.913421] Code: 00000000 00000000 00000000 00000000 (d7082c80)

**Comment by micsuka** [comment]
I forgot to mention that it's CM7-rc1, but I had problem with almost every ROM I tried. Maybe it's a hardware issue.

**Comment by maniac103** [comment]
This really looks like a hardware or kernel issue, neither of which we can fix. I'm sorry to say that, but this is a bug tracker, not a help forum :) Please ask that kind of questions at the appropriate places (e.g. xda-developers forum). Thanks.
