### ISSUE TITLE
problems in calls with sip accounts registers

### ISSUE THREAD

**Issue by MarceloMachadoxD** [CyanogenDefy/android_device_motorola_jordan#47]
i got only problems with calls when:
register sip accounts
turn on the internet (wifi or another)
use sip account to call - i got error on frist try, but in seccond, it´s works
after use sip acconts to make a call i dont have sucess to complete another calls using the normal calls, to complete i need turn of and turn on again the phone.. sometimes reboot does not make effect

**Comment by maniac103** [comment]
As we only track Defy-specific issues here, please report this to the CM bug tracker: http://www.cyanogenmod.com/bugs. Thanks!

**Comment by MarceloMachadoxD** [comment]
but this is specifc cyanogen mod by quarx
http://forum.xda-developers.com/showthread.php?t=1033654
for motorola defy users

and not a official build of cyanogen

**Comment by maniac103** [comment]
But the SIP code is not Defy specific, it's CM (or rather AOSP) code - unless there's evidence that your specific problem only occurs on the Defy...

**Comment by MarceloMachadoxD** [comment]
allrigth, tnx and sorry to flood with this here, i will try post in bug tracker of CM =) cya o/
