### ISSUE TITLE
Geotags incorrect in the photos

### ISSUE THREAD

**Issue by simsoo** [CyanogenDefy/android_device_motorola_jordan#49]
I only noticed yesterday that the geotags can be accessed through the photos from the gallery while the CM7 on the Defy.
Upload you to Picasa, the photo but are not highly evaluated the GPS data.
With the photos of my old N78 that works without problems.
Seems to be a bug in the CM7 or the camera app?

Can anyone confirm this?

**Comment by maniac103** [comment]
I guess the same problem happened with the stock ROM as well?

**Comment by simsoo** [comment]
I have found the error. In Exif-Data is "GPSLatitudeRef" not set (Unknown). 
If I put manually "GPSLatitudeRef" to "North" Picasa detects the GPS data.
Can you fix this error.
"GPSLongitudeRef" is always set correctly to East.

**Comment by maniac103** [comment]
In my pictures (SOC camera, which camera type do you have?) GPSLatitudeRef is set correctly. Besides that, I don't think we can fix incorrectly written exif data, because it's written by the proprietary Motorola library.
And you didn't answer my question - this problem also exists in the stock ROM, right?

**Comment by simsoo** [comment]
I have a green lens. Unfortunately I have not tried the stock rom.

**Comment by simsoo** [comment]
http://www.android-hilfe.de/motorola-defy-forum/121825-kamera-speichert-bilder-mit-negativen-vorzeichen-fuer-den-breitengrad-ab.html#post1689619

**Comment by simsoo** [comment]
I have tried it with the Stock Rom (Froyo Rom Build 3.4.2_179-002). The error is the same. GPSLatitudeRef is wrong set to W.
Can you fix this in CM7?

**Comment by maniac103** [comment]
Fixed: https://github.com/CyanogenDefy/android_device_motorola_jordan/commit/594a5d8e49a842fbfdabf4a3c844bf6be710f701
The workaround is ugly as hell, but gets the job done.
