### ISSUE TITLE
mp4 playback issues

### ISSUE THREAD

**Issue by AL2** [CyanogenDefy/android_device_motorola_jordan#5]
tested on June 10th, June 13th and boot-177 nightly builds. 

issues:
- mp4 playback suffers from bad video artifacts (solarized-like on various -but always the same spot- video sections) on both stock "Movies" player and RockPlayer (in HW mode).
- audio/video sinch delay from the start and gets worst if time seek function is used
- video freezes on resuming playback (RockPlayer)
- video playback experience is very bad when switching between various points of storyline.

Issues started post June 8th (cm7-110608-0020-NIGHTLY-Jordan) and have been observed with both:

Official Chinese Froyo: [JDGC_U6_1.11.0_SIGNED_USAJRDNPRCB1B50AA02F.0R_JORDANGCCORE_P011_A030_HWp3_Service1FF.sbf]

and Nordic Froyo:
[JRDNEM_U3_3.4.2_177-005_NORDIC_SIGN_SIGNED_UCAJRDNEMARAB1B80AA03A.0R_PDS03C_USAJRDNFRYORTNORD_P003_A001_HWp3_Service1FF.sbf]

as base.

Chinese red lense Defy

**Comment by Quarx2k** [comment]
Can you upload video which has artifacts?
Thanks.

**Comment by tpruvot** [comment]
if you need old changelog in OMX, you can check the old repo, i keep it under tpruvot/android_device_motorola_umts_jordan

**Comment by AL2** [comment]
Can you upload video which has artifacts?
Thanks.

Quarx: 

The video I'm usually doing my tests with is 67MB in size and I would not know how to send it over to you or how to put it on a file hosting site - I'm really sorry for that. 

It's a 8-9 minutes long Metallica live concert FLV video that I've re-encoded to 640x362 pixels on my PC using Handbrake software. [and Just to be clear: that has nothing to do with videos taken from my Defy's camera]

Every video works perfectly and never skips a beat with RC0, but for any nightly build mentioned on my OP, it's a nightmare.  It feels like I'm trying to watch 1080HD movie on a 10-15 years old laptop with integrated graphics: it is that bad once you start playing with time-seek (jump to different spots within the video w or w/o pausing playback first). Those time-seek related problems should be really easy for anyone to reproduce with any mp4 video -->I had problems with every mp4s on my Defy; it is not a 'one-video-only' issue. I only use that one because it is easy to see if the drums, guitar solos and vocals are in sync with the video.

The artifacts are like smudges or like rendering problems that an over-heating desktop video card would give.
Those happen at specific places in the video; so it could be partially due to encoding errors --> but why can RC0 play those parts without any problems and nightly builds don't...? Were there any changes on anything video/audio codecs related made around June 9th builds?

OK, it's too late tonight for this; but let me do this: I'll do my best to find some time (tomorrow - maybe) to try a new(er) nightly build again. I will try to find a smaller video which exibits problems then email it to you with my findings. 

Again sorry: I write a lot here, but don't feel like I give you much relevant info/material for problem solving....

[i might have closed  this post by mistake...I don't know, but it should not be...]

**Comment by Quarx2k** [comment]
You can upload video to http://ge.tt

**Comment by AL2** [comment]
Done!

Tried it with cm7-110621-1406-NIGHTLY-Jordan.zip and get exact same problem.

I will now try send the file to you by email.

Cheers

**Comment by Quarx2k** [comment]
Hm, i tested your video with 110621-1406 .. can't find any problem with playing it
I tried more different flv and mp4 .. no problem

Stock movie player and MoboPlayer with hw.

**Comment by AL2** [comment]
Well, all I can say is thanks a bunch for trying to reproduce my problem.

Tried again today with cm7-110622-1734:

from perfectly working RC0,
- factory reset, clear cache and Dalvik (too make sure none of my installed apps are causing the (codec?) problems
- skipped Google setup
- turned ON airplane mode
- did not install any apk or change any settings
- opened Gallery, let it scan SD card for media and redo library thumbnails
- selected and played the file I sent you with the system default "Movies" player

result: at exactly 25sec from the start: artifiacts again
- go back to gallery and play a bigger [live concert] mp4 video file
- let it play 10 sec, pause it and move a few minutes forward into the file and resumed playback

result: audio is clearly out of sync with video. Let it play a little more: artifacts at the exact same spots as noticed in other builds.

I really cannot see what I could be doing wrong here...
Could the Chinese Defy's specific hardware -like for the camera flash issues- have effects on audio/video playback as well?
--> if you answer yes to that; then why RC0 doesn't experience that ??????

# Edit:

[BTW- even if I'm on nordic, the SIM Toolkit is displayed in Chinese only - so there's a problem for it reading system language settings]
end of edit. #

It's been 5 or 6 nightly builds that I've tried now and the boot177 was even tried after a clean nordic flashing... 

So time for me to throw the towel and give up maybe. Unfortunately, I will have to accept that there is a bug specific to my phone and forget about testing out new nightly builds. RC0 is working pretty nicely for me and without any of those video playback bugs.

RC0 will then become my personal CM7 final release, which is fine with me BTW.

...although I admit that I will miss test driving new nightly builds and try help you guys with the CM7-jordan development. 

Take care guys and thanks again.

**Comment by AL2** [comment]
I'm emailing you guys (Quarx and Epsylon) a file showing my problems and comparing RC0 and RC1.

**Comment by tpruvot** [comment]
quarx made a change on codecs, i think it is in the 0625 nightly 
https://github.com/CyanogenDefy/android_hardware_ti_omap3/commit/21b2eb1fd70de05a4d73a5b60365fd3bdb511ffe

**Comment by shamo42** [comment]
I have the similar issue with RC1 and a German Defy. It's like some frames are displayed too early/late and the result is jerky playback. Maybe I'll upload a video later to show the problem.

**Comment by Quarx2k** [comment]
https://github.com/Quarx2k/android_frameworks_base/commit/2f2643e27bac33a8827caf314c123c0b57e12526
Maybe it help.

**Comment by ghost** [comment]
I can reproduce the problem simply playing a mp4/3GP video made by my defy when it had froyo ROM.

**Comment by AL2** [comment]
Quarx2k: https://github.com/Quarx2k/android_frameworks_base/commit/2f2643e27bac33a8827caf314c123c0b57e12526
Maybe it help.

So if I get this right, this is an attempt to fix audio/video sync issues only? 
Will it be included in a coming nightly? If so, I will be glad to give it a try when it is released.
Like I wrote on xda, 110625-1657 build did not bring any improvement for me.

That would still leave the video artifacts part pending...
I'm totally ignorant in the coding involved regarding this, but I guess that there is no quick and easy comparison between RC0 and current build regarding what changed in codecs to be done. Why is RC0 so perfect with video?

Thanks for keep trying ;-)

**Comment by shamo42** [comment]
It also happens for *.3gp files. I've uploaded a video that doesn't play properly with RC1:
http://www.multiupload.com/M43YPHELK7

This is what it looks like on the defy:
http://www.youtube.com/watch?v=tzOBgj1tu9w

**Comment by Quarx2k** [comment]
shame42:  i tested this video, it works without problems (after last my commit)

**Comment by AL2** [comment]
You've done it camarade! 

110627-1722 build fixed all my problems described here - AWESOME!!!!!!
I will test more thoroughly tomorrow; but again: so far, everything's perfect for me regarding video playback.
Even Shamo42's file wouldn't play in hardware decoding mode on June25th nightly; on this latest one, it does.

Again: you're THE MAN! 

You can cook Defy magic.

BIG THUMBSUP and many thanks

;-)

**Comment by shamo42** [comment]
Videos play fine with latest nightly! Thx!

**Comment by tpruvot** [comment]
so... could be pushed to CyanogenDefy :)

**Comment by Quarx2k** [comment]
Need re-test after cleanup code.
https://github.com/Quarx2k/android_frameworks_base/commit/f31dc98bfdcb621c4d4c12c36a745f5da5967bdc

**Comment by AL2** [comment]
I'm perfectly happy with RC1v2, but if I can help testing the code clean up, please just point me to the right nightly and I'll be glad to test it.

**Comment by Quarx2k** [comment]
latest nighlty include it.

**Comment by AL2** [comment]
OK, sorry for the delay; my battery was in the red zone after trying out RC1v2 for over 40 hours....

I've just installed 110629-0746-NIGHTLY [without wiping data but did wipe cache, Dalvik and battery stats as usual) and I'm glad to report that I've seen no issues with video playback with it: 
everything looks good!

;-)

**Comment by Quarx2k** [comment]
Thanks:)
