### ISSUE TITLE
Vídeo recording problem

### ISSUE THREAD

**Issue by eversonleal** [CyanogenDefy/android_device_motorola_jordan#50]
I'm was recording a simple video with the YouTube resolution and the recording stops automatically and the video file is corrupted. Ps. I'm still have space in my SD card

**Comment by LeopardSurd** [comment]
Maybe you just pressed accidentally the home button. In this case the recording stops automatically and the video file is corrupt. Also, the camera app is unusable (FC) if you wanna re-open but it until the restart of the phone. It is a known bug and depends of what nightly use. All the RC-s versions have this bug. Try to duplicate it and confirm. Doesn't matter if is a YouTube resolution, Wide or Normal.

**Comment by eversonleal** [comment]
Ok... confirmed..

**Comment by LeopardSurd** [comment]
Use the 11 July nightly. It doesn't has it.
