### ISSUE TITLE
No software can record the calling sound! CM7-RC1

### ISSUE THREAD

**Issue by arcol** [CyanogenDefy/android_device_motorola_jordan#54]
The double-way calling sound(incoming and outgoing sound) cannot be record in same time. I think it is a problem of core module

**Comment by AL2** [comment]
I don't think this is an issue that should be posted here.
The in-call recording option is just not included or implemented in CM7-jordan...yet.
Will it ever be? I don't know.

So your entry is more like a wishlist one than bug report....

(I miss that option from my stock ROM too BTW).

**Comment by maniac103** [comment]
AL2, you're completely right. Also, this request is not Defy specific. Please report it to the CM bug tracker: http://code.google.com/p/cyanogenmod/issues/list
