### ISSUE TITLE
no video camera flash "wide resolution"- green lens

### ISSUE THREAD

**Issue by maurink6630** [CyanogenDefy/android_device_motorola_jordan#57]
Video Flashlight for red camera has been already fixed  (good job maniac103)

But the flash for green lens still does not work at videorecording on wide resolution
(RC1v2 and all nightly)

**Comment by maurink6630** [comment]
always in widescreen resolution there are also problems with the zoom

**Comment by maniac103** [comment]
This is fixed now.
