### ISSUE TITLE
Android Market

### ISSUE THREAD

**Issue by scratchy** [CyanogenDefy/android_device_motorola_jordan#58]
Hiho

Got some problems with Market, (cant find for example: google mail). Market Website doesnt work anymore
(https://market.android.com/) wanted to install google+ for example. It says my device isnt compatible with this app :(.

Thanks and Happy Fixing ^_~

**Comment by killigrew** [comment]
thats not a bug in the rom! :(

google mail ist offline at the moment because they are updating it to 2.3.5 i think.

if it sais the app is incompatible, than it is propably not available in your country.
Search for Market Enabler at google and you will find a way around it. :)

**Comment by maniac103** [comment]
Indeed. And in any case, this is certainly not a Defy specific problem.
