### ISSUE TITLE
Camera crashes during incoming call while recording a video (green lense)

### ISSUE THREAD

**Issue by xetz** [CyanogenDefy/android_device_motorola_jordan#61]
While i was recording a video a friend called me, after the call the camera software crashed. I needed to reboot, to fix it. furthermore the video file wasn´t useable. I got the cm7 rc1v2 mod, would be cool if somebody could fix this.
nevertheless this mod is awesome fast, thx!

mfG xetz

cm7 rc1v2

**Comment by maniac103** [comment]
Dupe of #34.
