### ISSUE TITLE
wifi problem with modem zoom x>4

### ISSUE THREAD

**Issue by gaubu84** [CyanogenDefy/android_device_motorola_jordan#62]
I got wifi problem with modem zoom x>4, i mean modem zoom series x5, x6, x.....
I'm using moto defy T-mobile US. Can you solve this problem in cm7?
With this modem, as before, I can connect easy when using original froyo rom from T-mobile US, my Iphone 4 can connect easily as well. 
However, when I move to CM7 updated 11/07/2011 and other order version, my defy got problem ( found the signal strength well but disconnect without obtaining) while my iphone 4 show stabality working with wifi.
Can you help CM7 work well as the original froyo rom from T-mobile US in wifi connection?
Thank you so much indeed,

**Comment by jaskle** [comment]
My English is not good, I can not get WIFI IP, I do so:
“Menu-Search”
then get IP

**Comment by gaubu84** [comment]
cm7 updated 15/7 solved the problem with wifi.
