### ISSUE TITLE
RC1v2 - Problems with 3D games

### ISSUE THREAD

**Issue by thiagold** [CyanogenDefy/android_device_motorola_jordan#64]
I'm still having problems with any 3D game. I have installed on my Defy the following ones:

Contract Killer (the worst)
Can Knockdown 2
Last Stand Lite
Trial X Demo

When I'm using Contract Killer, I have the felling that the processor hit 100% usage (just a feeling).

How can I help to solve this issue?
What more information I'm able to collect to help solving this one?

PS: This problems never happens while using Beta 6

**Comment by jaskle** [comment]
I found that all games work well with my RC1V2.
but....I never played "Contract Killer", I want to try.
I hope the Chinese version...

**Comment by thiagold** [comment]
My problem was solved formating wipe, data, dalvic and reinstalled RC1v2 again.
