### ISSUE TITLE
problem with media player (wma files)

### ISSUE THREAD

**Issue by gaubu84** [CyanogenDefy/android_device_motorola_jordan#65]
CM7 updated 15/7 is so great, however, I still get the problem with media file (wma files) while with original rom from T-mobile, I have no problem with those media file. That means CM7 can not play wma file and some file like that. It now just can play mp3 files. Can you fix this problem with CM7 for motorola defy?
Thank you so much in advanced,

**Comment by Quarx2k** [comment]
stagefright does not support WMA

**Comment by gaubu84** [comment]
Thank Quarx2k for your quick reply,
But why when I installed soft:  "Poweramp" player, it can play all media (including wma) smoothly and this let me think that there's way for CM7 to play wma files.

**Comment by Quarx2k** [comment]
Poweramp use software encoding for wma.
