### ISSUE TITLE
unlock screen --> security lock

### ISSUE THREAD

**Issue by mauropanzeri** [CyanogenDefy/android_device_motorola_jordan#70]
I'm on cm7-110719-0852-NIGHTLY (other infos on the bottom) on my Defy and set the pattern-security-lockscreen:
now i have the unlock-screen and after that i must unlock the pattern-security-lockscreen.
I don't want both of them, i just want the pattern-security-lockscreen
I've checked the option "Disable the lockscreen if security screen lock is enabled" in CyanoGenMod menu, but the unlock-screen keep appearing before the pattern-security-lockscreen. 
Rebooted, wiped cache... no effects.

I searched on the net but i couldn't find if it's a bug (CM7/defy) or not.
It's only me or it's a bug of the latest nightlies? 

Other Infos: i installed CM7 RC1v2 with the usual way (flash nordic... reboot... recovery... etc) then i've started the phone, rebooted, wiped cache/davilk/batterystats, and flashed  cm7-110719-0852-NIGHTLY-Jordan through "stable recovery".
## 

edit: the nightly is  cm7-110719-0852-NIGHTLY (not the 110721).

**Comment by killigrew** [comment]
hmm, i cannot confirm the problem.
I'm on cm7-110721-0808-NIGHTLY and i'm using the pattern-screen, too
for me everything is as normal, only pattern key is shown, no lock-screen.
try to wipe cache and check every setting.

greetings

**Comment by mauropanzeri** [comment]
The unique settings that i find related is:
 settings--> CyanoGenMod --> lockscreen--> "disable unlock-screen if security lock is enabled" 
and is enabled/checked.

wiped cache, wiped davilk.
I tried to uncheck/recheck it and rebooting. no effects

could you check your status of that setting?

**Comment by killigrew** [comment]
for me, the settings is enabled.

**Comment by mauropanzeri** [comment]
The very first time i flashed nordic sbf and then the latest nightly. that time i hadn't this issue.
After that i've reflashed  nordic sbf, then flashed RC1v2 (they told it has a kernel update) and then flashed the nightly.

Do you know of any other settings involved in this?
Did you flashed directly a nightly or did you flashed RC1v2 and then updated to the nightly?

**Comment by killigrew** [comment]
i flash new nightlys since rc0, im using the 179 kernel.
But I don't think this matters in this case.
Is the bug still there in latest nightly's?
Are you using any lockscreen related app?

**Comment by tpruvot** [comment]
this feature is recent, was fixed since

thanks to help killigrew
