### ISSUE TITLE
mobile network - Basebandswitcher

### ISSUE THREAD

**Issue by chc2** [CyanogenDefy/android_device_motorola_jordan#71]
on my defy i installed the CyanogenMod 7 (Android 2.3.4) RC1v2 [Update: 28.06.2011]

with my eplus-Network (mobile) i have no chance to get online, so i tried to install with ClockWorkMod v4.0.0.6-defy

 Baseband.zip oder MY_RECEPTION_FIX.zip per ClockworkMod

both failed with the Info:

Amend scripting (update-script) is no longer supported.
Amend scripting was deprecated by Google in Android 1.5
It was necessary to remove it when upgrading to the clockworkmod 3.0 Gingerbread based recovery.
Please switch to edify scripting (updater-script and update-binary) to create working update zip packages.
Installation aborted.

so what can i do to get the mobile network ?

thx 
chc

**Comment by killigrew** [comment]
This is a bugtracker not a service hotline, plz :)
this isn't even related to cm7 but is caused by cwm3.
use the baseband switcher app for that, no need to flash anything
its already there in you app drawer. :)
