### ISSUE TITLE
Typo in german translation

### ISSUE THREAD

**Issue by frogking** [CyanogenDefy/android_device_motorola_jordan#74]
Hi,

I found some typos and will start with this one:

in packages/apps/Email/res/values-de/strings.xml

Wrong: <string name="show_hidden_action">Verteckte Ordner zeigen</string>

Correct: <string name="show_hidden_action">Versteckte Ordner zeigen</string>

Thanx,

Frogking

**Comment by killigrew** [comment]
hi, these are upstream bugs of cm and are not defy related.
you have to post them there :)

greetings

**Comment by frogking** [comment]
Hi killigrew, 

thanks for the info. It's a little bit like being in the jungle with all these dozens of repos, but  Ithink I finally found what I've been looking for :-).
