### ISSUE TITLE
password for android exchange client NOT! encrypted 

### ISSUE THREAD

**Issue by robidick** [CyanogenDefy/android_device_motorola_jordan#75]
The password for the android MS-Exchange client is fully viewable in /data/system/accounts.db! This security risk must be fixed.
Regards
Robidick

**Comment by killigrew** [comment]
but not in here, this is only for bugs which are defy related.
You have to post to the main cm bug tracker.

greetings

**Comment by maniac103** [comment]
Indeed. In fact, there's already an entry in the android bug tracker for this issue: http://code.google.com/p/android/issues/detail?id=10809
