### ISSUE TITLE
few bugs/issues in rc1/nightlies

### ISSUE THREAD

**Issue by jzakarias** [CyanogenDefy/android_device_motorola_jordan#77]
camera (both rc1/nightlies, green lens):
- in sunny conditions the phone rarely can take a photo (tried all settings, none of them solves it), when taking a picture, part of the screen turns to a random color, the app freezes, and it doesnt save the pic.
- when recording a video, it sometimes freezes when i stop recording, and doesnt save the video (also tried all settings)
- video recording is a bit choppy, but way better than it was in rc1 (nightly 110727-2117, and i think the devs are aware of this problem).
  wifi:
- for some reason the 'regulatory domain' setting from wireless/wifi/advanced was removed in the nightlies after rc1, and it is set to 11 channels by default, cant connect to networks running on more than 11 channels (eg. my home network).
- wifi indicator on the notification bar sometimes turns grey.
- wifi randomly reports 'obtaining ip address' even though there are no networks nearby, and the only thing that solves this is turning wifi on/off.

**Comment by maniac103** [comment]
For getting the regulatory domain settings back, find the ro.debuggable setting in build.prop and set it to 1.

**Comment by jzakarias** [comment]
cant find anything like ro.debuggable in build.prop, and ive looked through it quite thoroughly.

**Comment by maniac103** [comment]
Sorry, it's in /system/bootmenu/config/default.prop.

**Comment by jzakarias** [comment]
thank you so much, been looking for a solution for weeks now :)

**Comment by jzakarias** [comment]
so... the camera freeze was because i applied the camera patch with too little compression, and the module couldnt take it (damn soc). the things with video recording seem to be solved in the 110822 boot179. wifi now works properly, but the indicator color-bug is still there, but i dont think it will annoy anybody. :) so im closing this issue now.
