### ISSUE TITLE
bluetooth hid keyboard does not properly connect.

### ISSUE THREAD

**Issue by lamed** [CyanogenDefy/android_device_motorola_jordan#82]
My keyboard is known to be working, I checked it with Samsung galaxy s running stock froyo and with an iphone, which demonstrated no problems at all.
Trying to connect with cm7 RC1 (I have tried beta 6 and up): it's very easy to go through the pairing process and get android to say "connected to hid device", but there is no input coming from the keyboard - I cannot type or move through menus.
(I have tried unchecking the hid profile under the keyboard's option menu, and other settings combinations)
Using either bluekeyboard jp or blueinput (they are bluetooth keyboard drivers), I can actually get input from the keyboard, but these drivers hang and disconnect after a short while. I don't know why the bt communication is dropped. same thing happen to me like this guy:
 http://www.teksoftco.com/forum/viewtopic.php?f=30&t=2787&p=6865&hilit=defy#p6865

here's my post in the forum about this problem which shows more people have the same problem:
 http://forum.xda-developers.com/showthread.php?p=16176926#post16176926 

I asked on irc if this bug should be filed to cm7 bugtracker, but since cm7 is not released yet for the defy, the answer was no.

"bluetooth keyboard easyconnect" is using bluez tools and is another bluetooth keyboard driver made by an xda member, it does not work for me. (its designed to work when you're stuck with a "paired but not connected" message, which is not this case. I have fiddled with every possible setting combination. my shot in the dark is: cm7 has a built in hid profile, which is failing, and won't let easyconnect to do its thing)
 http://forum.xda-developers.com/showthread.php?t=925474

 let me know if I can be of more help.

**Comment by maniac103** [comment]
I don't know who gave you the answer that this bug shouldn't be filed to the CM7 tracker, but it's definitely wrong: The HID support is not Defy specific, but generic CM7 code.
Before reporting it to the CM7 tracker, please try the latest nightly. There was some HID related patch which went into CM7 in the last days.

**Comment by lamed** [comment]
thanks for your comment.
would you be able to direct me to instructions about how to install a nightly? I figured that the defy code will be on a different "branch" and wouldn't get updated automatically with cm7. (I understand this was wrong, but my initial question remains.) 
thanks!

**Comment by maniac103** [comment]
Download a nightly from here: http://defycm7.tanguy.tk/ and flash it like you did with RC1.
