### ISSUE TITLE
DSP WiLL FORCE CLOSE WHEN DIALING

### ISSUE THREAD

**Issue by BadRomance** [CyanogenDefy/android_device_motorola_jordan#86]
Dsp ( sound enhance app ) will force close when dialing ( a bubble popped up )

And , I downloaded  OTHER KEYBOARDS LIKE "THUMBS  KEYBOARD" ( AN APK) AND INSTALLED , WHEN I USE IT , IT WILL FORCE CLOSE , EVEN OTHER KEYBOARDS I DOWNLOADED DO THE SAME ......

**Comment by maniac103** [comment]
Please provide logcat output from after the crash. You can use alogcat (https://market.android.com/details?id=org.jtb.alogcat) to do that.

Also, there's no need for all caps.

**Comment by BadRomance** [comment]
Sorry but my keyboard was out of order sometimes , it will switch as "it"  like when i'm typing. Anyway, I changed my keyboard now ^^ 

I will post the output when it occur again.  Thanks
