### ISSUE TITLE
GPS power consumption issue

### ISSUE THREAD

**Issue by ScratMan** [CyanogenDefy/android_device_motorola_jordan#87]
Used the GPS with Google Maps and Navigation, and I lost 50% of the battery capacity in 2 hours, while the phone was plugged on a 1.2A car charger.

When using the stock leaked Beta ROM 4.5.1-134 (Gingerbread), the battery was able to charge when plugged on a 950 mA car charger when using GPS applications.

**Comment by maniac103** [comment]
The battery stops charging when it gets very hot. May this have been the case for you? Perhaps it was very warm that day?
FWIW, I have seen both cases for me already: On a very warm day, it stopped charging, but usually it works. Both cases are with CM7 and running Sygic.

**Comment by ScratMan** [comment]
It was a nice day, not warm at all, and the battery is warming up mainly because of the power consumption of the phone.

I'm now trying the 2011-08-09 nightly version, I'll test it with GPS to confirm if the power consumption is lower or not (some guys told the autonomy was better on the latest nightlies).

**Comment by ScratMan** [comment]
I did some more tests today, with the nigthly from 2011/08/09.

I saw that when using the GPS, the temperature of the battery could reach 54°C (I'm using a SoEasy Rider  rainproof housing to attach the Defy on my motorbike, it may degrade the thermal performance).
The battery was charging at the beginning of my trip, but at the end, it couldn't charge. So it may be related to temperature.

Do you know what is the maximum battery temperature threshold for charging the Defy ?

I tried without the GPS (function and apps) but letting the screen on (with auto luminance, but with the sun shining today, it was using the max luminance), the temperature decreased to 46-47°C, but it still couldn't charge. I had to switch off the screen to the battery charged.
