### ISSUE TITLE
Restore DLNA

### ISSUE THREAD

**Issue by amalweezy** [CyanogenDefy/android_device_motorola_jordan#88]
How can i restore DLNA app from stock back up....can i do this through rom manager.......

**Comment by maniac103** [comment]
This is a bug tracker, not a forum.
The DLNA app has dependencies into the framework of the stock ROM, so it's not possible to (easily) port it over. It would need some serious patching to the app to get it to work on CM7, if it's at all possible.
We likely won't do that, as there are alternatives in the market.
