### ISSUE TITLE
3G Watchdog not auto launching

### ISSUE THREAD

**Issue by thiagold** [CyanogenDefy/android_device_motorola_jordan#9]
Start using 3G with 3G Watchdog running ok. Then I change to wifi connection than watchdog goes down. When I switch back to 3G connection, watchdog do not raise back.

I will report this issue to Watchdog developer too.

**Comment by charlie2alpha** [comment]
I'm using 3G Watchdog Pro, I didn't notice any problems...

**Comment by thiagold** [comment]
I will force this situation at home and try to scan anything at aLogcat to see if helps.

**Comment by thiagold** [comment]
I started the 3GW manually and then I notice that it was working, but the icon was not being showed.
