### ISSUE TITLE
(110816-1425)Leaving 3G+Data ON restarts the system every time

### ISSUE THREAD

**Issue by Zerobarat1** [CyanogenDefy/android_device_motorola_jordan#90]
If the user let's the system go into standby with 3G and Data ON, the system will always crash. It happens 5/5 times and last try sent me into a boot-loop. 
 MB525 Green Lenses

**Comment by maniac103** [comment]
Does this also happen if the phone is connected via USB? If yes, it would be very good if you could
- install the Android SDK
- run 'adb logcat' and let it run
- wait until the crash
- post the full output of adb logcat here

**Comment by Zerobarat1** [comment]
No it does not occur via USB. In my case just leaving the device to sleep with 3G+Data on was sufficient for it to restart. Also unfortunately, I don't use that build anymore, I went back to 0813-2132. 
 Cheers and sorry I could not be more helpfull
