### ISSUE TITLE
Bunny!

### ISSUE THREAD

**Issue by Anton111111** [CyanogenDefy/android_device_motorola_jordan#91]
Where is bunny from boot logo? We all like this bunny ;-)

**Comment by tpruvot** [comment]
https://github.com/CyanogenDefy/android_device_motorola_jordan

logo_bunny.img

^^

the one in bootmenu : https://github.com/CyanogenDefy/android_device_motorola_jordan/blob/gingerbread/bootmenu/images/background.png
