### ISSUE TITLE
wireless tethering addons

### ISSUE THREAD

**Issue by chem57guru** [CyanogenDefy/android_device_motorola_jordan#95]
I just installed the 0822 nightly and the wireless tethering works great!

Is there anyway that the wireless tethering could be made into a widget that we could get to through the pull down menu where all the other widgets are?  Like where the wireless, bluetooth, gps, etc widgets are?  Or make them into a widget we can put on our home screen?  Keep up the good work this rom is awesome!

Chem57guru

**Comment by loosethisskin** [comment]
There is already such a widget: Widgets -> Power Control -> Portable Wi-Fi hostspot
