### ISSUE TITLE
tether wifi through usb

### ISSUE THREAD

**Issue by drod7** [CyanogenDefy/android_device_motorola_jordan#98]
I can tether my 3g fine through usb but can't share wifi through USB. If u dont understand basically I want my defy to act as USB wifi stick. It seems to want to work but doesn't. I know what your saying why would I want to to this? Because I use my neighbors wifi cuz I don't have internet and sometimes I don't pay my simple Mobile on time lol. Thanks for taking the time to read this. I hope it is something that can be fixed. 

Sent from my Google Defy.

**Comment by maniac103** [comment]
Actually, this works just fine for me. Please elaborate on what exactly doesn't work:
- Does the PC side interface get an IP assigned?
- Can you ping the Defy from the PC?
- Does DNS resolution work (try e.g. ping www.google.com' to see)?

**Comment by drod7** [comment]
yes PC side does get a ip but it never lets me access the internet at all . 3g USB tether is not what i want to do and it does work. i want to WiFi USB tether. i think i cannot ping defy.

**Comment by maniac103** [comment]
Forgot to say: Should be fixed now.
