### ISSUE TITLE
Contact specific ringtones do not play

### ISSUE THREAD

**Issue by gluttonyx** [CyanogenDefy/android_device_motorola_jordan#99]
ringtones set for contacts do not play when that contact calls, only the globally set ringtone plays. I have tried RC1 v2 and RC1.5 and there is no difference...

I have also tried using zedge to set the contact ringtone but it still doesnt work.

**Comment by charlie2alpha** [comment]
Only have specific ringtone for one contact and it works fine as far as I can tell. Running RC1.5 currently.

**Comment by gluttonyx** [comment]
Looks like it was facebook's contact sync that was confusing things, I wondered why the contact picture looked different when people rang! de-synced facebook contacts and everything worked fine!
